[package]
name = "rename"
version = "2.0.0"
edition = "2021"
license = "MIT"
description = "Clean all episode names in current directory"
repository = "https://github.com/patrickramp/rename"
categories = ["command-line-utilities"]

[dependencies]
regex = "1.10.5"
